In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files

uploaded = files.upload()

Saving streaming_users_dirty.json to streaming_users_dirty.json

In [ ]:
df = pd.read_json("streaming_users_dirty.json")

In [ ]:
df.head()

,user_id,age,subscription_plan,monthly_watch_time_mins,country,favorite_genre,last_login_date,customer_support_tickets
0,10000,39,Estándar,805.8,Brasil,Crime,2025-03-04,99
1,10001,37,Estándar,1173.4,Colombia,Crime,2019-04-02,2
2,10002,28,Básico,401.0,Colombia,Crime,2018-04-13,0
3,10003,43,Básico,62.4,Uruguay,Thriller,2021-01-31,0
4,10004,51,Básico,477.8,Perú,Thriller,2020-09-30,1

In [ ]:
df.shape

(8160, 8)

El dataset contiene alrededor de 1363 entradas, con ocho columnas adjacentes

In [ ]:
list(df.columns)

['user_id',
 'age',
 'subscription_plan',
 'monthly_watch_time_mins',
 'country',
 'favorite_genre',
 'last_login_date',
 'customer_support_tickets']

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8160 entries, 0 to 8159
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   user_id                   8160 non-null   int64
 1   age                       8160 non-null   int64
 2   subscription_plan         8160 non-null   object
 3   monthly_watch_time_mins   7967 non-null   float64
 4   country                   8160 non-null   object
 5   favorite_genre            7920 non-null   object
 6   last_login_date           7840 non-null   object
 7   customer_support_tickets  8160 non-null   int64
dtypes: float64(1), int64(3), object(4)
memory usage: 510.1+ KB

Se observan variables numéricas y categóricas. Algunas columnas corresponden a datos cuantitativos mientras que otras almacenan información textual.

In [ ]:
df.describe()

,user_id,age,monthly_watch_time_mins,customer_support_tickets
count,8160.000000,8160.000000,7967.000000,8160.000000
mean,13995.433824,34.096814,1107.346153,1.800980
std,2310.810660,14.511304,5310.442604,11.334969
min,10000.000000,-5.000000,-120.000000,-1.000000
25%,11987.750000,25.000000,489.200000,0.000000
50%,13998.500000,33.000000,757.400000,1.000000
75%,15997.250000,42.000000,1045.700000,1.000000
max,17999.000000,150.000000,99999.000000,150.000000

In [ ]:
df.describe(include="object")

       subscription_plan country favorite_genre last_login_date
count               8160    8160           7920            7840
unique                15      26             28            3062
top               Básico  Brasil        Comedia      2026-15-03
freq                3450    1132           1112              20

In [ ]:
df.isnull().sum()

user_id                       0
age                           0
subscription_plan             0
monthly_watch_time_mins     193
country                       0
favorite_genre              240
last_login_date             320
customer_support_tickets      0
dtype: int64

In [ ]:
df.duplicated().sum()

np.int64(126)

In [ ]:
for columna in df.columns:
    print(columna)
    print(df[columna].unique())
    print("-"*40)

user_id
[10000 10001 10002 ... 17997 17998 17999]
----------------------------------------
age
[ 39  37  28  43  51  20  31  36  23  46  15  45  29  24  35  32  30  17
  33  18  40  42  22  44  41  59  26  25  27  53   0  55  34  47  16  21
  13  38  56  19  48  14  57  52  64  60  58 130  54  50  49  61  66  73
 150  -5  68   4  69  62  72  63  67  65  76  80  74  71  70]
----------------------------------------
subscription_plan
['Estándar' 'Básico' 'Premium' 'Std' 'estandar' 'basico' 'básico'
 'Premium ' 'premium' 'Premiun' 'BASICO' 'STANDARD' 'Basic' 'Estándar '
 'PREMIUM']
----------------------------------------
monthly_watch_time_mins
[ 805.8 1173.4  401.  ...  410.4  501.4 1574.8]
----------------------------------------
country
['Brasil' 'Colombia' 'Uruguay' 'Perú' 'Chile' 'Argentina' 'México'
 'Brazil' 'brasil' 'méxico' 'chile' 'uruguay' 'MEX' 'ARG' 'colombia' 'COL'
 'Mexico' 'URY' 'Chile ' 'Peru' 'perú' 'argentina' 'PER' 'Argentina '
 'BRA' 'CHL']
----------------------------------------
favorite_genre
['Crime' 'Thriller' 'Drama' 'Acción' 'Romance' 'Comedia' 'Documental'
 'ACCIÓN' None 'CRIME' 'Comedia ' 'comedy' 'DRAMA' 'THRILLER'
 'Documentary' 'Thriller ' 'accion' 'Action' 'COMEDIA' 'ROMANCE' 'thriler'
 'DOC' 'romance' 'Crimen' 'Drama ' 'drama' 'Romance ' 'documental' 'crime']
----------------------------------------
last_login_date
['2025-03-04' '2019-04-02' '2018-04-13' ... '2018-06-25' '2019/04/30'
 '2025-07-19']
----------------------------------------
customer_support_tickets
[ 99   2   0   1   3   4 150  -1   5]
----------------------------------------

En esta corta revision se puede apreciar que, no solo hay datos faltantes y otrors erroneos si no tembien, hay, datos erroneos, como, por ejmplo, uno de los pacientes infantes teninedo una edad de -1